"""Relational rubric models, contracts, and repository helpers."""

from .contracts import (
    CountBandConfig,
    CriterionDefinition,
    CurriculumAlignmentConfig,
    DomainDefinition,
    FormDefinition,
    LlmRubricGuidanceConfig,
    RatioBandConfig,
    ShortSampleConfig,
    StrategyConfig,
    ValidationIssue,
    ValidationReport,
    canonicalize_form,
)
from .manifests import (
    AGENT_MANIFEST_REGISTRY_V1,
    get_agent_manifest,
)
from .models import (
    EvaluationFormSnapshot,
    RubricAgentActivation,
    RubricCriterion,
    RubricDomain,
    RubricSet,
)
from .repository import (
    activate_revision,
    create_draft_from_active,
    delete_draft_revision,
    get_active_form_definition,
    get_form_definition_by_id,
    load_active_form_definitions,
    lock_activation_and_revisions,
    lock_and_load_requested_active_forms,
    lock_draft_rubric_set,
    orm_to_form_definition,
    publish_draft_revision,
    retire_revision,
    validate_form_definition,
)
from .service import get_active_rubric_context
from .snapshot_contracts import (
    EvaluationFormSnapshotDTO,
    EvaluationFormSnapshotPayload,
    SnapshotIntegrityError,
    build_evaluation_form_snapshot,
    compute_snapshot_hash,
    serialize_snapshot_payload,
    verify_evaluation_form_snapshot,
)
from .snapshots import (
    load_verified_evaluation_snapshots,
    persist_evaluation_form_snapshots,
    resolve_or_reuse_evaluation_snapshots,
)

__all__ = [
    "AGENT_MANIFEST_REGISTRY_V1",
    "CountBandConfig",
    "CriterionDefinition",
    "CurriculumAlignmentConfig",
    "DomainDefinition",
    "EvaluationFormSnapshot",
    "EvaluationFormSnapshotDTO",
    "EvaluationFormSnapshotPayload",
    "FormDefinition",
    "LlmRubricGuidanceConfig",
    "RatioBandConfig",
    "RubricAgentActivation",
    "RubricCriterion",
    "RubricDomain",
    "RubricSet",
    "ShortSampleConfig",
    "SnapshotIntegrityError",
    "StrategyConfig",
    "ValidationIssue",
    "ValidationReport",
    "activate_revision",
    "build_evaluation_form_snapshot",
    "canonicalize_form",
    "compute_snapshot_hash",
    "create_draft_from_active",
    "delete_draft_revision",
    "get_active_form_definition",
    "get_active_rubric_context",
    "get_agent_manifest",
    "get_form_definition_by_id",
    "load_active_form_definitions",
    "load_verified_evaluation_snapshots",
    "lock_activation_and_revisions",
    "lock_and_load_requested_active_forms",
    "lock_draft_rubric_set",
    "orm_to_form_definition",
    "persist_evaluation_form_snapshots",
    "publish_draft_revision",
    "resolve_or_reuse_evaluation_snapshots",
    "retire_revision",
    "serialize_snapshot_payload",
    "validate_form_definition",
    "verify_evaluation_form_snapshot",
]
